[package]
name = "bachkhoa.typ"
version = "0.1.0"
compiler = "0.13.0"
authors = ["The TTB-HCMUT Developers <ttb-hcmut@protonmail.com>"]
repository = "https://github.com/ttb-hcmut/.github/tree/main/bachkhoa"

[template]
path = "template"
entrypoint = "template.typ"
thumbnail = "thumbnail.png"
